Repository uccser/cs-field-guide, pull requests merged in 2018-03, with the labels that each got.

#576 Update sorting and searching interactives
  interactives/searching-algorithms/c2runtime.js
  interactives/searching-algorithms/data.js
  interactives/searching-algorithms/icon-114.png
  interactives/searching-algorithms/icon-128.png
  interactives/searching-algorithms/icon-16.png
  interactives/searching-algorithms/icon-32.png
  interactives/searching-algorithms/instructions.txt
  interactives/searching-algorithms/offline.appcache
  interactives/searching-algorithms/project-files/searching-algorithms.capx
  interactives/sorting-algorithms/appmanifest.json
  interactives/sorting-algorithms/c2runtime.js
  interactives/sorting-algorithms/data.js
  interactives/sorting-algorithms/icon-114.png
  interactives/sorting-algorithms/icon-128.png
  interactives/sorting-algorithms/icon-16.png
  interactives/sorting-algorithms/icon-32.png
  interactives/sorting-algorithms/index.html
  interactives/sorting-algorithms/instructions.txt
  interactives/sorting-algorithms/offline.appcache
  interactives/sorting-algorithms/project-files/sorting-algorithms.capx
Labels: bug, interactives

#585 Issue/453 - checking image files can be found in project
  csfieldguide/chapters/content/en/chapters/artificial-intelligence.md
  csfieldguide/chapters/content/en/chapters/coding-compression.md
  csfieldguide/chapters/management/commands/_ChapterLoader.py
  csfieldguide/static/img/chapters/alice-chatbot-screenshot.png
  csfieldguide/static/img/chapters/cleverbot-chatbot-screenshot.png
  csfieldguide/static/img/chapters/compressed-jpeg-zoomed-highlighted.png
  csfieldguide/static/img/chapters/compressed-jpeg-zoomed.png
  csfieldguide/static/img/chapters/compressed-jpeg.png
  csfieldguide/static/img/chapters/compression-comparison.png
  csfieldguide/static/img/chapters/computer-studying-turing-test.png
  csfieldguide/static/img/chapters/cosine-graph.png
  csfieldguide/static/img/chapters/eliza-chatbot-screenshot.png
  csfieldguide/static/img/chapters/jpeg-word-zoomed.jpg
  csfieldguide/static/img/chapters/jpeg-word.jpg
  csfieldguide/static/img/chapters/pixel-diamond.png
  csfieldguide/static/img/chapters/sine-waves-sum.png
  csfieldguide/static/img/chapters/sine-waves.png
  csfieldguide/static/img/chapters/turing-test-dating-show.png
  csfieldguide/static/img/chapters/zoomed-eye-highlighted.png
  csfieldguide/static/img/chapters/zoomed-eye.png
  csfieldguide/static/interactives/high-score-boxes/img/thumbnail.png
  csfieldguide/tests/utils/__init__.py
  csfieldguide/tests/utils/test_find_image_files.py
  csfieldguide/utils/BaseLoader.py
  csfieldguide/utils/check_required_files.py
Labels: backend, testing

#587 Updated dockerfile to use latest uccser docker image
  Dockerfile
  requirements/base.txt
Labels: infrastructure, review needed
