Repository uccser/cs-field-guide, pull requests merged in 2018-10, with the labels that each got.

#745 Add menu-keystrokes interactive to replace image in HCI chapter
  csfieldguide/chapters/content/en/human-computer-interaction/sections/usability-heuristics.md
  csfieldguide/interactives/content/en/interactives.yaml
  csfieldguide/interactives/content/structure/interactives.yaml
  csfieldguide/static/scss/website.scss
  csfieldguide/templates/interactives/menu-keystrokes.html
Labels: interactives, internationalization

#746 Add binary-mode-calculator interactive to replace image in HCI chapter
  csfieldguide/chapters/content/en/human-computer-interaction/sections/usability-heuristics.md
  csfieldguide/interactives/content/en/interactives.yaml
  csfieldguide/interactives/content/structure/interactives.yaml
  csfieldguide/static/interactives/binary-mode-calculator/scss/binary-mode-calculator.scss
  csfieldguide/templates/interactives/binary-mode-calculator.html
Labels: interactives, internationalization

#749 Activate HCI chapter
  csfieldguide/chapters/content/structure/structure.yaml
  csfieldguide/interactives/content/structure/interactives.yaml
Labels: content: chapters

#754 Algorithms tidy up for translations
  csfieldguide/chapters/content/en/algorithms/algorithms.md
  csfieldguide/chapters/content/en/algorithms/sections/searching.md
  csfieldguide/static/interactives/high-score-boxes/js/script.js
Labels: content: chapters, interactives, internationalization

#761 Fix compilation of production JavaScript
  csfieldguide/gulpfile.js
  csfieldguide/package.json
  docker-compose.yml
Labels: backend, bug, frontend, urgent

#763 Remove pointer events for 'uninteractives'
  csfieldguide/static/scss/website.scss
  csfieldguide/templates/interactives/binary-mode-calculator.html
  csfieldguide/templates/interactives/confused-buttons.html
  csfieldguide/templates/interactives/confusing-error.html
  csfieldguide/templates/interactives/off-by-one.html
Labels: frontend

#765 Copy jsi18n to staticfiles.
  csfg
Labels: bug

#774 Consistent numbering for chapter sections
  csfieldguide/chapters/management/commands/_ChapterSectionsLoader.py
  csfieldguide/templates/chapters/chapter.html
  csfieldguide/templates/chapters/chapter_section.html
  csfieldguide/tests/chapters/loaders/assets/chapter-sections/en/non-sequential-section-numbers/non-sequential-section-numbers-section-1.md
  csfieldguide/tests/chapters/loaders/assets/chapter-sections/en/non-sequential-section-numbers/non-sequential-section-numbers-section-2.md
  csfieldguide/tests/chapters/loaders/assets/chapter-sections/en/non-sequential-section-numbers/non-sequential-section-numbers-section-4.md
  csfieldguide/tests/chapters/loaders/assets/chapter-sections/structure/non-sequential-section-numbers/non-sequential-section-numbers.yaml
  csfieldguide/tests/chapters/loaders/test_chapter_sections_loader.py
Labels: bug, frontend

#777 Update quicksort-interactive-step-1 image
  csfieldguide/static/img/chapters/quicksort-interactive-step-1.png
Labels: internationalization
