Repository uccser/cs-field-guide, pull requests merged in 2019-05, with the labels that each got.

#923 Activate AI Chapter
  csfieldguide/chapters/content/en/artificial-intelligence/artificial-intelligence.md
  csfieldguide/chapters/content/en/artificial-intelligence/sections/chatterbots-and-the-turing-test.md
  csfieldguide/chapters/content/en/artificial-intelligence/sections/further-reading.md
  csfieldguide/chapters/content/structure/structure.yaml
  csfieldguide/static/img/chapters/Turing_Test_version_3.png
  csfieldguide/static/img/chapters/alice-chatbot-screenshot.png
  csfieldguide/static/img/chapters/cleverbot-chatbot-screenshot.png
Labels: content: chapters

#920 Split 'Further reading' from 'The whole story!' in HCI chapter
  csfieldguide/chapters/content/en/human-computer-interaction/sections/further-reading.md
  csfieldguide/chapters/content/en/human-computer-interaction/sections/the-whole-story.md
  csfieldguide/chapters/content/structure/human-computer-interaction/sections/sections.yaml
Labels: content: chapters, frontend

#930 Do not check default interactive thumbnail paths
  csfieldguide/static/interactives/2d-shape-manipulations/img/thumbnail.png
  csfieldguide/static/interactives/base-calculator/img/thumbnail.png
  csfieldguide/static/interactives/big-number-calculator/img/thumbnail.png
  csfieldguide/static/interactives/bin-packing/img/thumbnail.png
  csfieldguide/static/interactives/binary-cards/img/thumbnail.png
  csfieldguide/static/interactives/box-rotation/img/thumbnail.png
  csfieldguide/static/interactives/box-translation/img/thumbnail.png
  csfieldguide/static/interactives/colour-matcher/img/thumbnail.png
  csfieldguide/static/interactives/delay-analyser/img/thumbnail.png
  csfieldguide/static/interactives/high-score-boxes/img/thumbnail.png
  csfieldguide/static/interactives/huffman-tree/img/thumbnail.png
  csfieldguide/static/interactives/image-bit-comparer/img/thumbnail.png
  csfieldguide/static/interactives/jpeg-compression/img/thumbnail.png
  csfieldguide/static/interactives/mips-assembler/img/thumbnail.png
  csfieldguide/static/interactives/mips-simulator/img/thumbnail.png
  csfieldguide/static/interactives/packet-attack/img/thumbnail.png
  csfieldguide/static/interactives/parity/img/thumbnail.png
  csfieldguide/static/interactives/pixel-viewer/img/thumbnail.png
  csfieldguide/static/interactives/regular-expression-search/img/thumbnail.png
  csfieldguide/static/interactives/rsa-jsencrypt/img/thumbnail.png
  csfieldguide/static/interactives/run-length-encoding/img/thumbnail.png
  csfieldguide/static/interactives/searching-algorithms/img/thumbnail.png
  csfieldguide/static/interactives/sorting-algorithms/img/thumbnail.png
  csfieldguide/static/interactives/trainsylvania-complete/img/english-solution.png
  csfieldguide/static/interactives/trig-function-calculator/img/thumbnail.png
  csfieldguide/static/interactives/viola-jones-face-detector/img/thumbnail.png
  csfieldguide/templates/interactives/trainsylvania-complete.html
  csfieldguide/tests/chapters/loaders/test_chapter_sections_loader.py
  csfieldguide/tests/chapters/loaders/test_chapters_loader.py
  csfieldguide/utils/BaseLoader.py
  csfieldguide/utils/check_required_files.py
  requirements/base.txt
Labels: backend

#904 Activate Complexity and Tractability chapter
  LICENCE-THIRD-PARTY
  csfieldguide/chapters/content/en/complexity-and-tractability/complexity-and-tractability.md
  csfieldguide/chapters/content/en/complexity-and-tractability/sections/algorithms-problems-and-speed-limits.md
  csfieldguide/chapters/content/en/complexity-and-tractability/sections/further-reading.md
  csfieldguide/chapters/content/en/complexity-and-tractability/sections/other-intractable-problems.md
  csfieldguide/chapters/content/en/complexity-and-tractability/sections/the-travelling-salesman-problem.md
  csfieldguide/chapters/content/en/complexity-and-tractability/sections/the-whole-story.md
  csfieldguide/chapters/content/en/complexity-and-tractability/sections/tractability.md
  csfieldguide/chapters/content/structure/complexity-and-tractability/sections/sections.yaml
  csfieldguide/chapters/content/structure/structure.yaml
  csfieldguide/interactives/content/en/interactives.yaml
  csfieldguide/interactives/content/structure/interactives.yaml
  csfieldguide/package.json
  csfieldguide/static/interactives/algorithm-timer/README.md
  csfieldguide/static/interactives/algorithm-timer/js/algorithm-timer.js
  csfieldguide/static/interactives/algorithm-timer/package.json
  csfieldguide/static/interactives/big-number-calculator/js/big-number-calculator.js
  csfieldguide/static/interactives/bin-packing/css/bin-packing.css
  csfieldguide/static/interactives/bin-packing/js/bin-packing.js
  csfieldguide/static/interactives/city-trip/README.md
  csfieldguide/static/interactives/city-trip/css/city-trip.css
  csfieldguide/static/interactives/city-trip/js/city-trip.js
  csfieldguide/static/interactives/city-trip/js/heapsAlgorithm.js
  csfieldguide/static/interactives/city-trip/package.json
  csfieldguide/templates/interactives/algorithm-timer.html
  csfieldguide/templates/interactives/big-number-calculator.html
  csfieldguide/templates/interactives/bin-packing.html
  csfieldguide/templates/interactives/city-trip.html
  third-party-licences/cytoscape-automove.txt
  third-party-licences/cytoscape-no-overlap.txt
  third-party-licences/cytoscapejs.txt
  third-party-licences/mathjs.txt
Labels: frontend, interactives, internationalization

#909 Issue/813 - Add LZW section to Coding - Compression chapter.
  csfieldguide/chapters/content/en/coding-compression/sections/general-purpose.md
  csfieldguide/interactives/content/en/interactives.yaml
  csfieldguide/interactives/content/structure/interactives.yaml
  csfieldguide/static/img/chapters/pixel-viewer-cartoon-values.png
  csfieldguide/static/img/chapters/pixel-viewer-photo-values.png
  csfieldguide/static/interactives/dictionary-compression/README.md
  csfieldguide/static/interactives/dictionary-compression/img/thumbnail.png
  csfieldguide/static/interactives/dictionary-compression/js/dictionary-compression.js
  csfieldguide/static/interactives/dictionary-compression/scss/dictionary-compression.scss
  csfieldguide/static/interactives/lzss-compression/README.md
  csfieldguide/static/interactives/lzss-compression/img/thumbnail.png
  csfieldguide/static/interactives/lzss-compression/js/lzss-compression.js
  csfieldguide/static/interactives/lzss-compression/scss/lzss-compression.scss
  csfieldguide/static/interactives/lzw-compression/README.md
  csfieldguide/static/interactives/lzw-compression/img/thumbnail.png
  csfieldguide/static/interactives/lzw-compression/js/lzw-compression.js
  csfieldguide/static/interactives/lzw-compression/scss/lzw-compression.scss
  csfieldguide/templates/interactives/dictionary-compression.html
  csfieldguide/templates/interactives/lzss-compression.html
  csfieldguide/templates/interactives/lzw-compression.html
Labels: author, bug, content: chapters, help wanted, interactives, review needed

#903 Activate NetCom Protocols Chapter
  LICENCE-THIRD-PARTY
  csfieldguide/chapters/content/en/network-communication-protocols/network-communication-protocols.md
  csfieldguide/chapters/content/en/network-communication-protocols/sections/application-level-protocols.md
  csfieldguide/chapters/content/en/network-communication-protocols/sections/further-reading.md
  csfieldguide/chapters/content/en/network-communication-protocols/sections/the-whole-story.md
  csfieldguide/chapters/content/en/network-communication-protocols/sections/transport-layer-protocols.md
  csfieldguide/chapters/content/en/network-communication-protocols/sections/what-is-a-protocol.md
  csfieldguide/chapters/content/structure/structure.yaml
  csfieldguide/gulpfile.js
  csfieldguide/interactives/content/en/interactives.yaml
  csfieldguide/interactives/content/structure/interactives.yaml
  csfieldguide/package.json
  csfieldguide/static/img/chapters/packet-structure-diagram.png
  csfieldguide/static/img/chapters/udp-encapsulation.png
  csfieldguide/static/interactives/packet-attack-level-creator/README.md
  csfieldguide/static/interactives/packet-attack-level-creator/css/packet-attack-level-creator.css
  csfieldguide/static/interactives/packet-attack-level-creator/css/packet-attack-level-creator.scss
  csfieldguide/static/interactives/packet-attack-level-creator/index.html
  csfieldguide/static/interactives/packet-attack-level-creator/js/packet-attack-level-creator.js
  csfieldguide/static/interactives/packet-attack/README.md
  csfieldguide/static/interactives/packet-attack/assets/background.png
  csfieldguide/static/interactives/packet-attack/assets/bluePacketExplosionSprites.png
  csfieldguide/static/interactives/packet-attack/assets/greenPacketExplosionSprites.png
  csfieldguide/static/interactives/packet-attack/assets/leftButton.png
  csfieldguide/static/interactives/packet-attack/assets/leftGreenButton.png
  csfieldguide/static/interactives/packet-attack/assets/middleButton.png
  csfieldguide/static/interactives/packet-attack/assets/pauseButton.png
  csfieldguide/static/interactives/packet-attack/assets/playButton.png
  csfieldguide/static/interactives/packet-attack/assets/redPacketExplosionSprites.png
  csfieldguide/static/interactives/packet-attack/assets/replayButton.png
  csfieldguide/static/interactives/packet-attack/assets/rightButton.png
  csfieldguide/static/interactives/packet-attack/assets/rightGreenButton.png
  csfieldguide/static/interactives/packet-attack/assets/startButton.png
  csfieldguide/static/interactives/packet-attack/css/packet-attack.scss
  csfieldguide/static/interactives/packet-attack/index.html
  csfieldguide/static/interactives/packet-attack/js/config.js
  csfieldguide/static/interactives/packet-attack/js/game.js
  csfieldguide/static/interactives/packet-attack/js/information.js
  csfieldguide/static/interactives/packet-attack/js/level.js
  csfieldguide/static/interactives/packet-attack/js/levelbuilder.js
  csfieldguide/static/interactives/packet-attack/js/packet-attack.js
  csfieldguide/static/interactives/packet-attack/js/packet.js
  csfieldguide/static/interactives/packet-attack/js/packetattack.js
  csfieldguide/static/interactives/packet-attack/js/phaserButton.js
  csfieldguide/static/interactives/packet-attack/libs/lodash.compat.min.js
  csfieldguide/static/interactives/packet-attack/libs/moment-duration-format.js
  csfieldguide/static/interactives/packet-attack/libs/moment.js
  csfieldguide/static/interactives/packet-attack/libs/phaser.map
  csfieldguide/static/interactives/packet-attack/libs/phaser.min.js
  csfieldguide/static/interactives/packet-attack/license.md
  csfieldguide/static/interactives/packet-attack/package.json
  csfieldguide/static/interactives/tcp-segment/css/tcp-segment.scss
  csfieldguide/static/interactives/udp-layers/css/udp-layers.scss
  csfieldguide/templates/interactives/packet-attack-level-creator.html
  csfieldguide/templates/interactives/packet-attack.html
  csfieldguide/templates/interactives/tcp-segment.html
  csfieldguide/templates/interactives/udp-layers.html
  third-party-licences/phaser3.txt
Labels: content: chapters, frontend, interactives, internationalization

#932 Change default button colour for bootstrap primary buttons.
  csfieldguide/static/interactives/awful-calculator/scss/awful-calculator.scss
  csfieldguide/static/scss/_core-variables.scss
  csfieldguide/templates/interactives/awful-calculator.html
Labels: frontend

#937 Copy over theme-colours object.
  csfieldguide/static/scss/_core-variables.scss
Labels: frontend

#936 Change navbar colours for table of contents.
  csfieldguide/static/scss/_core-variables.scss
  csfieldguide/static/scss/website.scss
  csfieldguide/templates/chapters/chapter_section.html
Labels: frontend

#938 Center fsa-washing-machine interactive in whole-page mode.
  csfieldguide/templates/interactives/fsa-washing-machine.html
Labels: bug, frontend

#941 Import codemiror css correctly.
  csfieldguide/static/scss/codemirror.scss
Labels: bug, frontend

#944 Set correct file path for import of codemirror css
  csfieldguide/static/scss/codemirror.scss
Labels: bug, frontend

#946 Improve usability of unicode chars and add readme
  csfieldguide/static/interactives/unicode-chars/README.md
  csfieldguide/static/interactives/unicode-chars/css/unicode-chars.css
  csfieldguide/static/interactives/unicode-chars/css/unicode-chars.scss
  csfieldguide/static/interactives/unicode-chars/js/unicode-chars.js
  csfieldguide/templates/interactives/unicode-chars.html
Labels: interactives, project style

#948 Remove .css extension.
  csfieldguide/static/scss/codemirror.scss
Labels: bug, frontend

#947 Fix old chapter link syntax in Algorithms chapter
  csfieldguide/chapters/content/en/algorithms/algorithms.md
Labels: backend, bug

#926 Activate Software Engineering chapter
  csfieldguide/chapters/content/en/software-engineering/sections/agile-software-development.md
  csfieldguide/chapters/content/en/software-engineering/sections/analysis.md
  csfieldguide/chapters/content/en/software-engineering/sections/design.md
  csfieldguide/chapters/content/en/software-engineering/sections/further-reading.md
  csfieldguide/chapters/content/en/software-engineering/sections/software-processes.md
  csfieldguide/chapters/content/en/software-engineering/sections/testing.md
  csfieldguide/chapters/content/en/software-engineering/sections/the-whole-story.md
  csfieldguide/chapters/content/en/software-engineering/software-engineering.md
  csfieldguide/chapters/content/structure/structure.yaml
  csfieldguide/interactives/content/en/interactives.yaml
  csfieldguide/interactives/content/structure/interactives.yaml
  csfieldguide/static/img/chapters/computer-layers.png
  csfieldguide/static/img/chapters/facebook-three-tier-system.png
  csfieldguide/static/img/chapters/iterative-software-development-diagram.png
  csfieldguide/static/img/chapters/waterfall-process-diagram.png
  csfieldguide/static/interactives/iterative-software-development/js/iterative-software-development.js
  csfieldguide/static/interactives/iterative-software-development/scss/iterative-software-development.scss
  csfieldguide/static/interactives/system-layers/img/applelogo-wikipedia.png
  csfieldguide/static/interactives/system-layers/img/cpu-dreamstime.png
  csfieldguide/static/interactives/system-layers/img/gclogo-wikipedia.png
  csfieldguide/static/interactives/system-layers/img/hdd-publicdomainpictures.png
  csfieldguide/static/interactives/system-layers/img/linuxlogo-wikipedia.png
  csfieldguide/static/interactives/system-layers/img/msedgelogo-wikipedia.png
  csfieldguide/static/interactives/system-layers/img/mswordlogo-wikipedia.png
  csfieldguide/static/interactives/system-layers/img/pc_user-pdclipart.png
  csfieldguide/static/interactives/system-layers/img/ram-wpclipart.png
  csfieldguide/static/interactives/system-layers/img/safarilogo-wikipedia.png
  csfieldguide/static/interactives/system-layers/img/win10logo-wikipedia.png
  csfieldguide/static/interactives/system-layers/scss/system-layers.scss
  csfieldguide/static/interactives/three-tier-website/img/cogs.png
  csfieldguide/static/interactives/three-tier-website/img/database_facebook.png
  csfieldguide/static/interactives/three-tier-website/img/zuckerberg_facebook.png
  csfieldguide/static/interactives/three-tier-website/scss/three-tier-website.scss
  csfieldguide/static/interactives/waterfall-process/js/waterfall-process.js
  csfieldguide/static/interactives/waterfall-process/scss/waterfall-process.scss
  csfieldguide/templates/interactives/iterative-software-development.html
  csfieldguide/templates/interactives/system-layers.html
  csfieldguide/templates/interactives/three-tier-website.html
  csfieldguide/templates/interactives/waterfall-process.html
Labels: content: chapters, internationalization, uninteractives

#951 Remove shadows from text editor in RE Search interactive
  csfieldguide/static/interactives/regular-expression-search/css/regular-expression-search.scss
  csfieldguide/templates/interactives/regular-expression-search.html
Labels: frontend

#955 Add crossorigin attribute to canvas elements.
  csfieldguide/templates/interactives/image-bit-comparer.html
  csfieldguide/templates/interactives/jpeg-compression.html
  csfieldguide/templates/interactives/pixel-viewer.html
Labels: bug

#956 Prevent canvas from being tainted by setting the crossorigin attribute in the JavaScript..
  csfieldguide/static/interactives/image-bit-comparer/js/image-bit-comparer.js
  csfieldguide/static/interactives/jpeg-compression/js/jpeg-compression.js
  csfieldguide/static/interactives/pixel-viewer/js/pixel-viewer.js
  csfieldguide/static/interactives/viola-jones-face-detector/js/viola-jones.js
Labels: bug

#952 Make iframe backgrounds transparent
  csfieldguide/static/scss/interactive-iframe.scss
  csfieldguide/templates/interactives/base/iframe.html
Labels: infrastructure, interactives

#890 Activate Programming Languages Chapter
  LICENCE-THIRD-PARTY
  csfieldguide/chapters/content/en/programming-languages/programming-languages.md
  csfieldguide/chapters/content/en/programming-languages/sections/a-babel-of-programming-languages.md
  csfieldguide/chapters/content/en/programming-languages/sections/further-reading.md
  csfieldguide/chapters/content/en/programming-languages/sections/machine-code.md
  csfieldguide/chapters/content/en/programming-languages/sections/the-whole-story.md
  csfieldguide/chapters/content/structure/structure.yaml
  csfieldguide/interactives/content/structure/interactives.yaml
  csfieldguide/static/interactives/mips-assembler/README.md
  csfieldguide/static/interactives/mips-assembler/css/mips-assembler.scss
  csfieldguide/static/interactives/mips-assembler/js/mips-assembler.js
  csfieldguide/static/interactives/mips-simulator/README.md
  csfieldguide/static/interactives/mips-simulator/css/mips-simulator.scss
  csfieldguide/static/interactives/mips-simulator/js/mips-simulator.js
  csfieldguide/static/interactives/python-interpreter/README.md
  csfieldguide/static/interactives/python-interpreter/css/python-interpreter.scss
  csfieldguide/static/interactives/python-interpreter/js/python-interpreter.js
  csfieldguide/templates/interactives/mips-assembler.html
  csfieldguide/templates/interactives/mips-simulator.html
  csfieldguide/templates/interactives/python-interpreter.html
  third-party-licences/mips-assembler.txt
  third-party-licences/mips-simulator.txt
  third-party-licences/skulpt.txt
Labels: content: chapters, frontend, interactives, internationalization

#957 At the end of each chapter, link to the next
  csfieldguide/chapters/views.py
  csfieldguide/templates/chapters/chapter_section.html
Labels: backend, frontend, suggestion

#962 Redirect the releases page to the changelog on ReadTheDocs
  csfieldguide/general/urls.py
  csfieldguide/tests/appendices/urls/test_changelog_url.py
Labels: backend

#963 Make sure cross origin attribute is set before the image source is.
  csfieldguide/static/interactives/image-bit-comparer/js/image-bit-comparer.js
  csfieldguide/static/interactives/jpeg-compression/js/jpeg-compression.js
  csfieldguide/static/interactives/pixel-viewer/js/pixel-viewer.js
  csfieldguide/static/interactives/viola-jones-face-detector/js/viola-jones.js
Labels: bug, interactives

#960 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: infrastructure, project style, suggestion

#961 update contributors page
  csfieldguide/templates/appendices/contributors.html
Labels: documentation

#966 Recreate flowcharts image as uninteractive
  csfieldguide/chapters/content/en/programming-languages/sections/how-does-the-computer-process-your-program.md
  csfieldguide/interactives/content/en/interactives.yaml
  csfieldguide/interactives/content/structure/interactives.yaml
  csfieldguide/static/img/chapters/comparing-sorting-programs-across-scratch-and-c.png
  csfieldguide/static/interactives/flowcharts-interpreter-compiler/js/flowcharts-interpreter-compiler.js
  csfieldguide/static/interactives/flowcharts-interpreter-compiler/scss/flowcharts-interpreter-compiler.scss
  csfieldguide/templates/interactives/flowcharts-interpreter-compiler.html
Labels: internationalization, uninteractives

#959 Add django translation tags to base html files
  csfieldguide/templates/appendices/about.html
  csfieldguide/templates/appendices/base.html
  csfieldguide/templates/appendices/contributors.html
  csfieldguide/templates/appendices/curriculum-guides/apcsp.html
  csfieldguide/templates/appendices/curriculum-guides/index.html
  csfieldguide/templates/appendices/curriculum-guides/ncea.html
  csfieldguide/templates/appendices/index.html
  csfieldguide/templates/appendices/sitemap.html
  csfieldguide/templates/base.html
  csfieldguide/templates/chapters/chapter.html
  csfieldguide/templates/chapters/chapter_section.html
  csfieldguide/templates/chapters/glossary.html
  csfieldguide/templates/chapters/index.html
  csfieldguide/templates/general/index.html
Labels: internationalization

#924 Activate Computer Vision chapter
  LICENCE-THIRD-PARTY
  csfieldguide/chapters/content/en/computer-vision/computer-vision.md
  csfieldguide/chapters/content/en/computer-vision/sections/edge-detection.md
  csfieldguide/chapters/content/en/computer-vision/sections/face-recognition.md
  csfieldguide/chapters/content/en/computer-vision/sections/further-reading.md
  csfieldguide/chapters/content/en/computer-vision/sections/noise.md
  csfieldguide/chapters/content/en/computer-vision/sections/the-whole-story.md
  csfieldguide/chapters/content/en/computer-vision/sections/thresholding.md
  csfieldguide/chapters/content/structure/structure.yaml
  csfieldguide/interactives/content/en/interactives.yaml
  csfieldguide/interactives/content/structure/interactives.yaml
  csfieldguide/package.json
  csfieldguide/static/interactives/pixel-viewer/js/pixel-viewer.js
  csfieldguide/static/interactives/pixel-viewer/scss/pixel-viewer.scss
  csfieldguide/static/interactives/viola-jones-face-detector/README.md
  csfieldguide/static/interactives/viola-jones-face-detector/css/viola-jones.css
  csfieldguide/static/interactives/viola-jones-face-detector/index.html
  csfieldguide/static/interactives/viola-jones-face-detector/js/viola-jones.js
  csfieldguide/static/interactives/viola-jones-face-detector/libs/interact.min.js
  csfieldguide/static/interactives/viola-jones-face-detector/libs/interactjs-LICENSE.md
  csfieldguide/static/interactives/viola-jones-face-detector/libs/tracking-min.js
  csfieldguide/static/interactives/viola-jones-face-detector/libs/trackingjs-LICENSE.md
  csfieldguide/static/interactives/viola-jones-face-detector/package.json
  csfieldguide/templates/interactives/pixel-viewer.html
  csfieldguide/templates/interactives/viola-jones-face-detector.html
  third-party-licences/tracking.txt
Labels: interactives, internationalization

#976 Remove reference to old searching interactive.
  csfieldguide/chapters/content/en/algorithms/sections/searching.md
Labels: content: chapters, frontend

#970 Add solution to SENG bridge building activity
  csfieldguide/chapters/content/en/software-engineering/sections/software-processes.md
  csfieldguide/static/img/chapters/card-bridge-solution.jpg
Labels: content: chapters, suggestion, user feedback
